# Getting and Cleanning Data Course

## Project Tasks
You should create one R script called run_analysis.R that does the following:

* Merges the training and the test sets to create one data set.
* Extracts only the measurements on the mean and standard deviation for each measurement.
* Uses descriptive activity names to name the activities in the data set
* Appropriately labels the data set with descriptive variable names.
* From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

## How to run the scripts

1. Downdload data zip file from [https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip] in your local drive
2. Unzip the file, you wil have a folder with name **UCI HAR Dataset**
3. Set your working directory to point on the above folder using **setwd()** or from the **More** menue in Files tab from RStudio
4. Place **run_analysis.R** in the above folder and load the file using **source("run_anaysis.R")**
5. Upon running the script new text file will be generated with name **tidy_data.txt**

## Prerequisite

you should load **reshape2** libarary

