# Code Book
This is a code book that describes the variables, the data, and any transformations or work that you performed to clean up the data.

## Data Sources
 * Data Sets:[https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip]
 * Data Set Description:[http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones]
 
## Data Set Information - UCI

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data.

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain.
 
## Project Data
 The following files are availabe for the date:
 
 1. **'features.txt'**: List of all features.
 2. **'activity_labels.txt'**: Links the class labels with their activity name.
 3. **'train/X_train.txt'**: Training data sets.
 4. **'train/y_train.txt'**: Training labels.
 5. **'test/X_test.txt'**: Test set.
 6. **'test/y_test.txt'**: Test labels.
 
## Required pacjages for Data Processing:
 1. **reshape2**
 
## Data Processing Steps - Transformation:
 1. Load the Test data and labels
 2. Load the Features names from features.txt
 3. Rename test data columns using the loaded features vector
 4. Extract only the measurements on the mean and standard deviation for each measurement.
 5. Bind X data with x labels
 6. Load activities and update ytest
 7. Bind xtest data with ytest data
 8. Apply steps from **1** to **7** an the train dataset
 9. merge the data generated form steps 7 and 8 in onw megred dataset
 10. calculate the mean of the data by applyig the dcast using mean function on th resulted data
 11. write the resulted data into txt file names **tiday_data.txt**
